---
abstract: 'calculate the percent change between two values'
author:
  - 'Mike Baas <mbaas@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-PercentChange
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Scalar::Util: 1.23
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
